config:
    - network:
        hostname: "arrakis"
        mode: "nmcli"
        iface: "ens18"
        base_ip: "10.0.0.4"
        netmask: "255.255.255.0"
    - users:
        - user:
            username: "arrakis"
            password: "4rrak1s_"
            groups: "arrakis"
            root: false
        - user:
            username: "root"
            password: "Harkonnen"
            groups: "root"
            root: true
    - flags:
        - flag:
            path: "/home/arrakis/user.txt"
            value: "df4a2bb8a4b8bf75c3364c7ebb5e58f6"
        - flag:
            path: "/root/root.txt"
            value: "17116e40a27c2349772cb14eb84ee7eb"
    apt-install: "python3"